# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Workflow Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: unit tests
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2.9.7
        with:
          command: npm run cypress:run
          start: npm run start-prod
          wait-on: http://localhost:5000

  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # Email that you use with heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          # The appname to use for deploying/updating
          heroku_app_name: bea-full-stack-open-pokedex
          healthcheck: "https://bea-full-stack-open-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          # Set this to true if you don't want to automatically create the Heroku app
          dontautocreate: true
          region: eu

  tag_release:
    if: ${{ github.event_name == 'push' }}
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DEFAULT_BUMP: "patch"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ github.event.commits.*.message }}
        run: echo "$COMMIT_MESSAGES"
